logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
#  datasource:
#    username: 
#    password: 
#    url: 
#    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create-drop
 
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        csv: text/csv
        xml: application/xml
        json: application/json
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${PORT:8080}
