logging:
  level:
    org:
      hibernate:
        SQL: debug
spring:
#Asignar datos de BD
  datasource: 
    username:
    password: 
    url: 
    driver-class-name: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create-drop
 
  mvc:
    contentnegotiation:
      favor-parameter: true
      media-types:
        pdf: application/pdf
        xlsx: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
        csv: text/csv
        xml: application/xml
        json: application/json
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: ${PORT:8080}
# Asignar credenciales de firebase
FIREBASE_BUCKET_NAME: 
FIREBASE_PROJECT_ID: 
FIREBASE_TYPE: 
FIREBASE_PRIVATE_KEY_ID: 
FIREBASE_PRIVATE_KEY: 
FIREBASE_CLIENT_EMAIL:
FIREBASE_CLIENT_ID: 
FIREBASE_AUTH_URI: 
FIREBASE_TOKEN_URI:
FIREBASE_AUTH_PROVIDER_X509_CERT_URL:
FIREBASE_CLIENT_X509_CERT_URL: 
